# Example 9: Single execution on Android Emulators and Android Real Devices
# Run all tests on any available *single* device in my pool, this can be US/EU

apiVersion: v1alpha
kind: espresso
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  # Controls how many suites are executed at the same time (sauce test env only).
  concurrency: 10
  metadata:
    tags:
      - android
      - espresso
      - ex9
    build: Sauce Espresso

espresso:
  app: ./apps/SauceLabs.Mobile.Sample.Espresso.App.apk
  testApp: ./apps/SauceLabs.Mobile.Sample.Espresso.Tests.apk

suites:
  - name: "Sauce Labs Espresso Tests from Example 9 - lockedUserLogin on an Emulator and Real Device"
    testOptions:
      class: ["com.swaglabsmobileapp.LoginTest#lockedUserLogin"]
    devices:
      - name: "Samsung.*"
        options:
          # Possible values [ANY,PHONE,TABLET]
          deviceType: PHONE
    emulators:
      - name: "Google Pixel C GoogleAPI Emulator"
        orientation: landscape
        platformVersions:
          - "8.1"
  - name: "Sauce Labs Espresso Tests from Example 9 - successfulLogin on an Emulator"
    testOptions:
      class: ["com.swaglabsmobileapp.LoginTest#successfulLogin"]
    emulators:
      - name: "Android GoogleApi Emulator"
        platformVersions:
          - "11.0"

# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./reports/
