# Example 10: Shard all tests over multiple instances
# Run all tests divided over multiple devices in my pool, this can be US/EU

apiVersion: v1alpha
kind: espresso
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  # Controls how many suites are executed at the same time (sauce test env only).
  concurrency: 10
  metadata:
    name: Testing Espresso Support
    tags:
      - android
      - espresso
      - ex1
    build: Sauce Espresso Sharding

espresso:
  app: ./apps/SauceLabs.Mobile.Sample.Espresso.App.apk
  testApp: ./apps/SauceLabs.Mobile.Sample.Espresso.Tests.apk

suites:
  - name: "Sauce Labs Espresso Tests from Example 10 - Shard All tests"
    testOptions:
      # use 4 instances to divide the tests over
      numShards: 4
    devices:
      - name: "Samsung.*"
        options:
          # Possible values [ANY,PHONE,TABLET]
          deviceType: PHONE
    emulators:
      - name: "Android GoogleApi Emulator"
        platformVersions:
          - "11.0"

# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./reports/
