# Example 6: Parallel execution by platform version
# Run two tests on separate specific devices in my pool, this can be US/EU.
#  Use `deviceNameQuery` to find any free Android device with Android 9 or 10
#  and run the test on it.

apiVersion: v1alpha
kind: espresso
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  # Controls how many suites are executed at the same time (sauce test env only).
  concurrency: 10
  metadata:
    tags:
      - android
      - espresso
      - ex6
    build: Sauce Espresso

espresso:
  app: ./apps/SauceLabs.Mobile.Sample.Espresso.App.apk
  testApp: ./apps/SauceLabs.Mobile.Sample.Espresso.Tests.apk

suites:
  - name: "Sauce Labs Espresso Tests from Example 6 - lockedUserLogin"
    testOptions:
      class: ["com.swaglabsmobileapp.LoginTest#lockedUserLogin"]
    devices:
      - name: "Samsung.*"
        platformVersion: 10
  - name: "Sauce Labs Espresso Tests from Example 6 - successfulLogin"
    testOptions:
      class: ["com.swaglabsmobileapp.LoginTest#successfulLogin"]
    devices:
      - name: "Samsung.*"
        platformVersion: 9

# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./reports/
